name: spinner_input_plus
description: A Spinner Input for flutter. Almost like html5 input-spinners, it has up/down buttons and also explicit value edit capability.
version: 0.0.2
homepage: https://github.com/CsabaConsulting/spinner_input_plus

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  intl: ^0.19.0
  flutter:
    sdk: flutter

dev_dependencies:
  analyzer: ^6.3.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
