name: spinner_input_plus
description: A Spinner Input for flutter. like html5 input-spinners
version: 0.0.1
homepage: https://github.com/CsabaConsulting/spinner_input_plus

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  intl: ^0.18.1
  flutter:
    sdk: flutter

dev_dependencies:
  analyzer: ^6.2.0
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
